"""
E-Book OCR Learned Corrections Engine & Knowledge Base Manager
스캔본 OCR 오탈자를 학습 데이터(data/learned_corrections.json) 및
체계적 정규식 규칙(180+ 규칙) 기반으로 우선 교정하고, 지속적으로 새로운 교정 지식을 저장/확장하는 모듈
"""

import os
import json
import re

BASE_DIR = os.path.dirname(os.path.abspath(__file__))
KB_PATH = os.path.join(BASE_DIR, "data", "learned_corrections.json")

def load_learned_kb():
    if not os.path.exists(KB_PATH):
        return {}
    try:
        with open(KB_PATH, "r", encoding="utf-8") as f:
            return json.load(f)
    except Exception as e:
        print(f"[KB Warning] Failed to load {KB_PATH}: {e}")
        return {}

def save_learned_kb(kb_data):
    os.makedirs(os.path.dirname(KB_PATH), exist_ok=True)
    temp_path = KB_PATH + ".tmp"
    with open(temp_path, "w", encoding="utf-8") as f:
        json.dump(kb_data, f, ensure_ascii=False, indent=2)
    if os.path.exists(KB_PATH):
        os.remove(KB_PATH)
    os.rename(temp_path, KB_PATH)

def add_learned_pair(wrong: str, correct: str, category: str = "기타"):
    kb = load_learned_kb()
    terms = kb.setdefault("terms", {})
    cat_dict = terms.setdefault(category, {})
    cat_dict[wrong] = correct
    save_learned_kb(kb)

# Precompile comprehensive regex rules for deep cleaning
COMPILED_PATTERNS = [
    (re.compile('vLLM\\s*서방'), 'vLLM 서빙'),
    (re.compile('서방까지'), '서빙까지'),
    (re.compile('\\b서방\\b(?=\\s*(?:하는|방법|원리|최적화|프레임워크|서버|엔진|을|를|이|가|은|는|에|으로))'), '서빙'),
    (re.compile('\\bVIM을\\s*활용한'), 'vLLM을 활용한'),
    (re.compile('\\bVIM\\b(?=\\s*(?:을|를|이|가|은|는|의|에|으로|에서))'), 'vLLM'),
    (re.compile('\\bVLLM\\b'), 'vLLM'),
    (re.compile('vLLM을\\s*활용하\\s*'), 'vLLM을 활용한 '),
    (re.compile('강다술'), '강다솔'),
    (re.compile('프로그래망'), '프로그래밍'),
    (re.compile('지용이\\s*강다슬'), '지은이 강다솔'),
    (re.compile('떠쭈이\\s*박찬규'), '도움이 박찬규'),
    (re.compile('없은이\\s*최용'), '엮은이 최용'),
    (re.compile('디치인\\s*북누리\\s*거지디지만'), '디자인 북누리 표지디자인'),
    (re.compile('떠고\\s*위키북스'), '펴낸곳 위키북스'),
    (re.compile('진사적\\s*솟판\\s*발행'), '초판 1쇄 발행'),
    (re.compile('첫페이지\\s*입니다:?'), ''),
    (re.compile('GemmarlLlama3|Gemma!Llama3'), 'Gemma 2 / Llama 3'),
    (re.compile('지침서가\\s*월\\s*것'), '지침서가 될 것'),
    (re.compile('자료가\\s*월\\s*것'), '자료가 될 것'),
    (re.compile('세계률'), '세계를'),
    (re.compile('기두길'), '거두길'),
    (re.compile('역사적\\s*맥리'), '역사적 맥락'),
    (re.compile('덥러님의'), '딥러닝의'),
    (re.compile('아기택처'), '아키텍처'),
    (re.compile('함\\s*끼'), '함께'),
    (re.compile('\\b종으\\b'), '좋으며'),
    (re.compile('바뀌\\s*학습해'), '바꿔 학습해'),
    (re.compile('셈풀\\s*데이터'), '샘플 데이터'),
    (re.compile('\\b셈풀\\b'), '샘플'),
    (re.compile('뚜딪이'), '뚜렷이'),
    (re.compile('유용하\\s*안내\\s*서'), '유용한 안내서'),
    (re.compile('등장까지루'), '등장까지'),
    (re.compile('인공지식에\\s*대한'), '인공지능에 대한'),
    (re.compile('지취서'), '지침서'),
    (re.compile('모는\\s*(분|이|코드|예제|사람|기업|데이터|독자|클라우드)'), '모든 \\1'),
    (re.compile('\\b다루녀\\b'), '다루며'),
    (re.compile('있도\\s*목'), '있도록'),
    (re.compile('트랜드록'), '트렌드를'),
    (re.compile('않게\\s*옮거나'), '얕게 다루거나'),
    (re.compile('\\b코램\\b'), '코랩'),
    (re.compile('\\b그처\\b'), '그쳐'),
    (re.compile('있없습니다'), '있었습니다'),
    (re.compile('심게\\s*따라을'), '쉽게 따라할'),
    (re.compile('\\b심게\\b'), '쉽게'),
    (re.compile('파\\s*인특딩'), '파인튜닝'),
    (re.compile('파인특딩'), '파인튜닝'),
    (re.compile('다른다는\\s*것입니\\s*다'), '다룬다는 것입니다'),
    (re.compile('짓러하브|짓허브'), '깃허브'),
    (re.compile('불렉하면'), '클릭하면'),
    (re.compile('다운로드I니다'), '다운로드됩니다'),
    (re.compile('찾아바도'), '찾아봐도'),
    (re.compile('카카오록'), '카카오톡'),
    (re.compile('오른채팅'), '오픈채팅'),
    (re.compile('우족\\s*상단의\\s*파라색'), '우측 상단의 파란색'),
    (re.compile('클렉합니다'), '클릭합니다'),
    (re.compile('실프\\s*어텐션'), '셀프 어텐션'),
    (re.compile('멀리하드|멀티해드'), '멀티헤드'),
    (re.compile('왜,d\\s*로나뉘야\\s*하느가'), '왜 sqrt(d_k)로 나누어야 하는가'),
    (re.compile('\\b지연어\\s*처리\\b'), '자연어 처리'),
    (re.compile('역전따\\s*알고리즘'), '역전파 알고리즘'),
    (re.compile('학습의\\s*적명'), '학습의 혁명'),
    (re.compile('\\b학명의\\b'), '혁명의'),
    (re.compile('트랜스포머의등장'), '트랜스포머의 등장:'),
    (re.compile('토근'), '토큰'),
    (re.compile('토풀'), '토큰'),
    (re.compile('임베당'), '임베딩'),
    (re.compile('\\b백터\\b'), '벡터'),
    (re.compile('어멘선'), '어텐션'),
    (re.compile('체크포인드'), '체크포인트'),
    (re.compile('허경페이스'), '허깅페이스'),
    (re.compile('생플림|심플렉'), '샘플링'),
    (re.compile('폐이지드\\s*어텐션'), '페이지드 어텐션'),
    (re.compile('이렇계'), '이렇게'),
    (re.compile('그렇계'), '그렇게'),
    (re.compile('쉽계'), '쉽게'),
    (re.compile('높계'), '높게'),
    (re.compile('어떻계'), '어떻게'),
    (re.compile('(노하우|벡터|잔차|엔터|루프|처리|변화|일치|요소)흘(?=\\s|$|[,\\.\\?!])'), '\\1를'),
    (re.compile('(순서|텐서|정보|콜레이터|코레이터|데코레이터|데고레이터|파라미터)클(?=\\s|$|[,\\.\\?!])'), '\\1를'),
    (re.compile('(길이|딕셔너리|덕서너리|라이브러리|의미|원리|디렉터리|디리터리)블(?=\\s|$|[,\\.\\?!])'), '\\1를'),
    (re.compile('(관계|비교|태스크|태스|기회)플(?=\\s|$|[,\\.\\?!])'), '\\1를'),
    (re.compile('불로그클'), '블록을'),
    (re.compile('차원율(?=\\s|$|[,\\.\\?!])'), '차원을'),
    (re.compile('\\b비레\\b'), '비례'),
    (re.compile('비레해'), '비례해'),
    (re.compile('이뤄저'), '이뤄져'),
    (re.compile('만들어저'), '만들어져'),
    (re.compile('작아저'), '작아져'),
    (re.compile('달라저'), '달라져'),
    (re.compile('밝혀저'), '밝혀져'),
    (re.compile('넓혀저'), '넓혀져'),
    (re.compile('([가-힣]+)되논지'), '\\1되는지'),
    (re.compile('([가-힣]+)하논지'), '\\1하는지'),
    (re.compile('([가-힣]+)있논지'), '\\1있는지'),
    (re.compile('([가-힣]+)되논(?=\\s)'), '\\1되는'),
    (re.compile('([가-힣]+)하논(?=\\s)'), '\\1하는'),
    (re.compile('([가-힣]+)있논(?=\\s)'), '\\1있는'),
    (re.compile('되엇으면'), '되었으면'),
    (re.compile('\\b이리한\\b'), '이러한'),
    (re.compile('너\\s*깊이'), '더 깊이'),
    (re.compile('사람이이\\s*분아에'), '사람이 이 분야에'),
    (re.compile('너\\s*깊이\\s*핑게'), '더 깊이 있게'),
    (re.compile('다충적인'), '다층적인'),
    (re.compile('어려\\s*움을'), '어려움을'),
    (re.compile('\\b쌍인\\b'), '쌓인'),
    (re.compile('팀험합니다'), '탐험합니다'),
    (re.compile('살펴건니다'), '살펴봅니다'),
    (re.compile('데이비드루델하트'), '데이비드 루멜하트'),
    (re.compile('제프리\\s*한튼[C]?'), '제프리 힌턴'),
    (re.compile('로W드\\s*월리임스|월리임스'), '로널드 윌리엄스'),
    (re.compile('맞이\\s*햇습니다'), '맞이했습니다'),
    (re.compile('않앗음에도'), '않았음에도'),
    (re.compile('위런\\s*맥걸록'), '워런 맥컬록'),
    (re.compile('임계\\s*논리관'), '임계 논리란'),
    (re.compile('임계값값'), '임계값'),
    (re.compile('커지고\\(활성화\\)'), '켜지고(활성화)'),
    (re.compile('도글드\\s*헤부'), '도널드 헤브'),
    (re.compile('너\\s*강하게'), '더 강하게'),
    (re.compile('혜부의\\s*이론'), '헤브의 이론'),
    (re.compile('농시에'), '동시에'),
    (re.compile('활성화월'), '활성화될'),
    (re.compile('강화답\\s*나다'), '강화됩니다'),
    (re.compile('웨술리\\s*콜라크'), '웨슬리 클라크'),
    (re.compile('컴퓨터률\\s*활용하'), '컴퓨터를 활용한'),
    (re.compile('만듬니\\s*다이?'), '만듭니다. 이'),
    (re.compile('만듬니다'), '만듭니다'),
    (re.compile('힐튼과\\s*콜라크'), '팔리와 클라크'),
    (re.compile('프행크\\s*로젠블랫'), '프랭크 로젠블랫'),
    (re.compile('코텔\\s*항공'), '코넬 항공'),
    (re.compile('만들어님니다'), '만들어냅니다'),
    (re.compile('미치\\s*논\\s*영향'), '미치는 영향'),
    (re.compile('맞춤니다'), '맞춥니다'),
    (re.compile("접근법'\\s*올\\s*따른니다"), '접근법을 따릅니다'),
    (re.compile('접근버에'), '접근법에'),
    (re.compile('농일한'), '동일한'),
    (re.compile('방법굳'), '방법론'),
    (re.compile('신뢰성\\s*핑게'), '신뢰성 있게'),
    (re.compile('퍼센트로은|퍼센드로이'), '퍼셉트론은'),
    (re.compile('퍼센트로'), '퍼셉트론'),
    (re.compile('구현되습니다'), '구현됐습니다'),
    (re.compile('작성되습니다'), '작성됐습니다'),
    (re.compile('역할을\\s*햇습니다'), '역할을 했습니다'),
    (re.compile("'밥울이라는"), "'밥'이라는"),
    (re.compile('나\\s*타법니다'), '나타냅니다'),
    (re.compile('사라집니대'), '사라집니다'),
    (re.compile('분꾸를'), '분포를'),
    (re.compile('최적화를\\s*동해'), '최적화를 통해'),
    (re.compile('실습을\\s*동해'), '실습을 통해'),
    (re.compile('이를\\s*동해'), '이를 통해'),
    (re.compile('덕서너리'), '딕셔너리'),
    (re.compile('디리터리'), '디렉터리'),
    (re.compile('파인[0-9가-힣]*[님낭딩빌넣]'), '파인튜닝'),
    (re.compile('파인튜-(?=\\s*\\(Fine-tuning\\))'), '파인튜닝'),
    (re.compile('파인튜닝이[관과]'), '파인튜닝이란'),
    (re.compile('파인튜닝중'), '파인튜닝 중'),
    (re.compile('파인튜닝을\\s*하늘\\s*이유'), '파인튜닝을 하는 이유'),
    (re.compile('하늘\\s*이유'), '하는 이유'),
    (re.compile('파라미터\\s*특[님늬냥녕]'), '파라미터 튜닝'),
    (re.compile('특[님늬냥녕](?=\\s*(?:기법|방식|을|를|이|가|은|는|의|에|으로|과|와))'), '튜닝'),
    (re.compile('\\bPET\\b(?=\\s*(?:기법|\\)))'), 'PEFT'),
    (re.compile('BFI6|BFtG'), 'BF16'),
    (re.compile('bfloatt6'), 'bfloat16'),
    (re.compile('F[PI]I?6|F머16'), 'FP16'),
    (re.compile('FP6\\)'), 'FP16)'),
    (re.compile('BFP16'), 'BF16'),
    (re.compile('16비I트'), '16비트'),
    (re.compile('32비I트'), '32비트'),
    (re.compile('부동소수제은'), '부동소수점은'),
    (re.compile('부동소수제(?=[이가을를의에과와])'), '부동소수점'),
    (re.compile('부동소수점와'), '부동소수점과'),
    (re.compile('정말도(?=\\s*(?:는|가|를|의|로|보다|틀))'), '정밀도'),
    (re.compile('\\b낯습니다\\b'), '낮습니다'),
    (re.compile('메모리\\s*사용랑'), '메모리 사용량'),
    (re.compile('\\b사용랑\\b'), '사용량'),
    (re.compile('호\\s*울성'), '효율성'),
    (re.compile('\\b렌서'), '텐서'),
    (re.compile('\\b넥터'), '벡터'),
    (re.compile('\\b디넥터리'), '디렉터리'),
    (re.compile('올티마이저'), '옵티마이저'),
    (re.compile('\\b올선(?=[과와을를은는이가])'), '옵션'),
    (re.compile('메거니[증롬좀름]'), '메커니즘'),
    (re.compile('메거니\\s*Value'), '메커니즘(Value'),
    (re.compile('출억'), '출력'),
    (re.compile('알고리[으증]'), '알고리즘'),
    (re.compile('컴퓨텅'), '컴퓨팅'),
    (re.compile('프로적트'), '프로젝트'),
    (re.compile('확물(?=[적인으로을를이가은는의과와도]|\\b)'), '확률'),
    (re.compile('학습물(?=[으로을를이가은는의과와도까지]|\\b)'), '학습률'),
    (re.compile('손실물(?=[으로을를이가은는의과와도]|\\b)'), '손실률'),
    (re.compile('\\b다[물률]\\b'), '다룰'),
    (re.compile('다물\\s*내용'), '다룰 내용'),
    (re.compile('\\b이틀(?=\\s+통해)'), '이를'),
    (re.compile('\\b예틀(?=\\s+들어)'), '예를'),
    (re.compile('FP32틀'), 'FP32를'),
    (re.compile('([A-Za-z0-9]+)틀(?=\\s|$|[,\\.\\?!])'), '\\1를'),
    (re.compile('(?<!기)(?<!\\b)([가-힣]{2,})틀(?=\\s|$|[,\\.\\?!])'), '\\1를'),
    (re.compile('(결과|효과|평가|역전파|성과|메시지|최적화|활성화|병렬화|이해|조직화)루(?=\\s|$|[,\\.\\?!])'), '\\1를'),
    (re.compile('(숫자|글자|문자|가중치|기중치|위치|절차)루(?=\\s|$|[,\\.\\?!])'), '\\1로'),
    (re.compile('기중치루'), '가중치로'),
    (re.compile('([A-Za-z0-9]+)올(?=\\s|$|[,\\.\\?!])'), '\\1을'),
    (re.compile('([가-힣]{2,})올(?=\\s|$|[,\\.\\?!])'), '\\1을'),
    (re.compile('([A-Za-z0-9가-힣]+)\\s+올(?=\\s|$|[,\\.\\?!])'), '\\1을'),
    (re.compile('\\b데이터지\\s*저장'), '데이터를 저장'),
    (re.compile('([가-힣]{2,})논데'), '\\1는데'),
    (re.compile('([가-힣]{2,})논(?=\\s)'), '\\1는'),
    (re.compile('([가-힣]{2,})눈(?=\\s+[가-힣]+(?:은|는|이|가|을|를|의|에|로|와|과|도))'), '\\1는'),
    (re.compile('([A-Za-z0-9_\\]\\)]+)눈(?=\\s)'), '\\1은'),
    (re.compile('([가-힣]*)해중니다'), '\\1해줍니다'),
    (re.compile('([가-힣]*)어중니다'), '\\1어줍니다'),
    (re.compile('([가-힣]*)려중니다'), '\\1려줍니다'),
    (re.compile('([가-힣]*)와중니다'), '\\1와줍니다'),
    (re.compile('([가-힣]*)줄여중니다'), '\\1줄여줍니다'),
    (re.compile('([가-힣]*)높여중니다'), '\\1높여줍니다'),
    (re.compile('([가-힣]*)가져움니다'), '\\1가져옵니다'),
    (re.compile('([가-힣]*)러움니다'), '\\1러옵니다'),
    (re.compile('([가-힣]*)여움니다'), '\\1여옵니다'),
    (re.compile('([가-힣]*)펴움니다'), '\\1펴봅니다'),
    (re.compile('([가-힣]*)제거움니다'), '\\1제거됩니다'),
    (re.compile('([가-힣]*)업로드움니다'), '\\1업로드됩니다'),
    (re.compile('([가-힣]*)시흉니다'), '\\1시됩니다'),
    (re.compile('([가-힣]*)비흉니다'), '\\1비됩니다'),
    (re.compile('([가-힣]*)바흉니다'), '\\1바뀝니다'),
    (re.compile('추천드럽니다'), '추천드립니다'),
    (re.compile('기다럽니다'), '기다립니다'),
    (re.compile('([가-힣]*)입나다'), '\\1입니다'),
    (re.compile('([가-힣]*)[임합습]나다'), '\\1니다'),
    (re.compile('생길니다'), '생깁니다'),
    (re.compile('빠름니다'), '빠릅니다'),
    (re.compile('유지켜까요'), '유지될까요'),
    (re.compile('줄어들/는데'), '줄어드는데'),
    (re.compile('사용-니다'), '사용됩니다'),
    (re.compile('수\\s*[엇핑잎앗D잇앞]게'), '수 있게'),
    (re.compile('([가-힣]+)활\\s*수\\s*있'), '\\1할 수 있'),
    (re.compile('만들없습니다'), '만들었습니다'),
    (re.compile('\\b쉽제\\b'), '쉽게'),
    (re.compile('패m'), '패턴'),
    (re.compile('[탤엘알][런럴]\\s*[튜특][껑립굉령링]'), '앨런 튜링'),
    (re.compile('[튜특][껑립굉령링]\\s*테스트'), '튜링 테스트'),
    (re.compile('[튜특][껑립굉령](?=[은는이가을를에게의와과도])'), '튜링'),
    (re.compile('로[젠전제]불?렉'), '로젠블랫'),
    (re.compile('퍼센트론'), '퍼셉트론'),
    (re.compile('조조지타운'), '조지타운'),
    (re.compile('조지타운-BM'), '조지타운-IBM'),
    (re.compile('어[텐렌린]선'), '어텐션'),
    (re.compile('실프\\s*어[렌텐]선'), '셀프 어텐션'),
    (re.compile('멀[티리][해하]드\\s*어[렌텐]선'), '멀티헤드 어텐션'),
    (re.compile('소포트맥스'), '소프트맥스'),
    (re.compile('모\\s*텔'), '모델'),
    (re.compile('첫지피티'), '챗지피티'),
    (re.compile('첫GPT'), 'ChatGPT'),
    (re.compile('도움이\\s*뵙니\\s*다'), '도움이 됩니다'),
    (re.compile('사고가\\s*발생있다'), '사고가 발생했다'),
    (re.compile('발생있다'), '발생했다'),
    (re.compile('유주은'), '유족은'),
    (re.compile('신고하지\\s*안고'), '신고하지 않고'),
    (re.compile('피해를\\s*키원다'), '피해를 키웠다'),
    (re.compile('일으권'), '일으킨'),
    (re.compile('형의를\\s*받흔다'), '혐의를 받는다'),
    (re.compile('받흔다'), '받는다'),
    (re.compile('받앗'), '받았'),
    (re.compile('잡앗'), '잡았'),
    (re.compile('뇌출변로'), '뇌출혈로'),
    (re.compile('뇌출변'), '뇌출혈'),
    (re.compile('내려적고'), '내려졌고'),
    (re.compile('시망있다'), '사망했다'),
    (re.compile('키위드'), '키워드'),
    (re.compile('\\b예\\s+들어,'), '예를 들어,'),
    (re.compile('들없다고'), '들었다고'),
    (re.compile('맛취'), '맞춰'),
    (re.compile('맛게'), '맞게'),
    (re.compile('맛춤'), '맞춤'),
    (re.compile('기중치\\s*패티이'), '가중치 패턴이'),
    (re.compile('패티이'), '패턴이'),
    (re.compile('기중치'), '가중치'),
    (re.compile('변경월\\s*수'), '변경될 수'),
    (re.compile('손실월\\s*수'), '손실될 수'),
    (re.compile('월\\s*수\\s*있'), '될 수 있'),
    (re.compile('저장되\\s*있던'), '저장돼 있던'),
    (re.compile('\\b하무로\\b'), '하므로'),
    (re.compile('\\b비레해\\b'), '비례해'),
    (re.compile('\\b이어저\\b'), '이어져'),
    (re.compile('연구자들\\s*에제'), '연구자들에게'),
    (re.compile('좌우염니다'), '좌우됩니다'),
    (re.compile('분아에는'), '분야에는'),
    (re.compile('인공지능\\s*분아'), '인공지능 분야'),
    (re.compile('\\b겨언이\\b'), '격언이'),
    (re.compile('데이터률'), '데이터를'),
    (re.compile('\\b십지\\s*않은'), '쉽지 않은'),
    (re.compile('\\b어려을\\s*수'), '어려울 수'),
    (re.compile('\\b운리적\\b'), '윤리적'),
    (re.compile('성-이나'), '성별이나'),
    (re.compile('높\\s*아집니다'), '높아집니다'),
    (re.compile('고려\\s*사랑입니다'), '고려 사항입니다'),
    (re.compile('머신러님'), '머신러닝'),
    (re.compile('떨어저도'), '떨어져도'),
    (re.compile('잎\\s*논'), '있는'),
    (re.compile('\\b잎는\\b'), '있는'),
    (re.compile('\\b업는\\b'), '없는'),
    (re.compile('\\b종은\\b(?=\\s+대안)'), '좋은'),
    (re.compile('\\b근\\s+규모'), '큰 규모'),
    (re.compile('\\b근\\s+문제'), '큰 문제'),
    (re.compile('제시햇\\s*습니다'), '제시했습니다'),
    (re.compile('비교하켓'), '비교하겠'),
    (re.compile('버티목'), '버팀목'),
    (re.compile('보젯습니다'), '보겠습니다'),
    (re.compile('신회할'), '신뢰할'),
    (re.compile('신회'), '신뢰'),
    (re.compile('뒷습니\\s*다'), '됐습니다'),
    (re.compile('뒷습니다'), '됐습니다'),
    (re.compile('워습니다'), '였습니다'),
    (re.compile('있엎습니다'), '있었습니다'),
    (re.compile('눈문'), '논문'),
    (re.compile('눈매'), '문맥'),
    (re.compile('있율까'), '있을까'),
    (re.compile('인용펼'), '인용될'),
    (re.compile('담구하기'), '탐구하기'),
    (re.compile('담구'), '탐구'),
    (re.compile('곁\\s*정짓는'), '결정짓는'),
    (re.compile('제안겠습니다'), '제안했습니다'),
    (re.compile('빛습니다'), '봤습니다'),
    (re.compile('주장쾌습니다'), '주장했습니다'),
    (re.compile('암는'), '않는'),
    (re.compile('알려저'), '알려져'),
    (re.compile('밭있\\s*습니다'), '받았습니다'),
    (re.compile('않앉다\\s*눈'), '않았다는'),
    (re.compile('제기행\\s*습니다'), '제기했습니다'),
    (re.compile('중요해적습니다'), '중요해졌습니다'),
    (re.compile('대화지'), '대화를'),
    (re.compile('생각활'), '생각할'),
    (re.compile('앞는\\s*지틀'), '있는지를'),
    (re.compile('앞는지'), '왔는지'),
    (re.compile('제시하습니다'), '제시했습니다'),
    (re.compile('앞게'), '있게'),
    (re.compile('앞는'), '있는'),
    (re.compile('콜라우드'), '클라우드'),
    (re.compile('콜래스|콤래스'), '클래스'),
    (re.compile('프콤프트'), '프롬프트'),
    (re.compile('콜라이언트'), '클라이언트'),
    (re.compile('인텍스'), '인덱스'),
    (re.compile('시권스'), '시퀀스'),
    (re.compile('임겟값'), '임계값'),
    (re.compile('자원의\\s*저주'), '차원의 저주'),
    (re.compile('자원\\s*축소'), '차원 축소'),
    (re.compile('전저리'), '전처리'),
    (re.compile('\\b저리\\b(?=\\s*(?:속도|시간|능력|과정|방법))'), '처리'),
    (re.compile('저리(할|하는|하고|해|된|될|되어|되지|하지|하면|하게|됨을|되기|됩니다|했습)'), '처리\\1'),
    (re.compile('자이점'), '차이점'),
    (re.compile(r'자이(가|를|로|에|의)'), r'차이\1'),
    (re.compile('사소한\\s*자이'), '사소한 차이'),
    (re.compile('큰\\s*자이'), '큰 차이'),
    (re.compile('독사들|독지들'), '독자들'),
    (re.compile('인고[딩당갈]'), '인코딩'),
    (re.compile('디고딩'), '디코딩'),
    (re.compile('디\\s*코딩'), '디코딩'),
    (re.compile('시푹스'), '시퀀스'),
    (re.compile('어답터'), '어댑터'),
    (re.compile('바[늄표]니다'), '바뀝니다'),
    (re.compile('처리워니다'), '처리됩니다'),
    (re.compile('분리\\}니다'), '분리됩니다'),
    (re.compile('취급되니\\s*다'), '취급됩니다'),
    (re.compile('([가-힣]+)되\\s*나다'), '\\1됩니다'),
    (re.compile('([가-힣]+)합니나다'), '\\1합니다'),
    (re.compile('([가-힣]+)됩니나다'), '\\1됩니다'),
    (re.compile('([합습입됩])\\s*나다'), '\\1니다'),
    (re.compile('([합습입])\\s+나다'), '\\1니다'),
    (re.compile('([합습입])니\\s+다'), '\\1니다'),
    (re.compile('([합습입됩])\\s+니\\s+다'), '\\1니다'),
    (re.compile('([합습입됩])\\s+니다'), '\\1니다'),
    (re.compile('순간이없습\\s*나다'), '순간이었습니다'),
    (re.compile('깨달\\s*앞습니다'), '깨달았습니다'),
    (re.compile('([가-힣]{2,})v\\b'), '\\1를'),
    (re.compile('네트위크'), '네트워크'),
    (re.compile('구조b\\b'), '구조는'),
    (re.compile('변환되는지루'), '변환되는지를'),
    (re.compile('사용활지루'), '사용할지를'),
    (re.compile('생성자루'), '생성자를'),
    (re.compile('작성자루'), '작성자를'),
    (re.compile('참가루'), '참가를'),
    (re.compile('참여자루'), '참여자를'),
    (re.compile('평기루'), '평가를'),
    (re.compile('한자루(?=\\s*구분)'), '한자를'),
    (re.compile('적자루(?=\\s*기록)'), '적자로'),
    (re.compile('전파루(?=\\s*과정)'), '전파 과정'),
    (re.compile('입\\s*턱\\s*시퀀스'), '입력 시퀀스'),
    (re.compile('확출\\s*분포'), '확률 분포'),
    (re.compile('포망팅'), '포매팅'),
    (re.compile('인종\\s*과정'), '인증 과정'),
    (re.compile('바군\\s*후'), '바꾼 후'),
    (re.compile('유호한'), '유효한'),
    (re.compile('토론(?=\\s*(?:이런|등)\\s*특수\\s*토[근큰])'), '토큰'),
    (re.compile('어려움을\\s*겨게'), '어려움을 겪게'),
    (re.compile('마게팅'), '마케팅'),
    (re.compile('수출화대'), '수출확대'),
    (re.compile('최약인'), '최악인'),
]

def apply_learned_knowledge(text: str) -> str:
    """학습 데이터베이스 및 정밀 규칙을 순차 적용하여 텍스트 정밀 교정"""
    if not text:
        return text
    
    # 1. Regex 패턴 적용
    t = text
    for pat, repl in COMPILED_PATTERNS:
        t = pat.sub(repl, t)
        
    # 2. Key-Value 딕셔너리 정밀 치환
    kb = load_learned_kb()
    terms = kb.get("terms", {})
    for cat_name, pair_dict in terms.items():
        for wrong, correct in pair_dict.items():
            if wrong in t:
                t = t.replace(wrong, correct)
                
    # 3. 띄어쓰기 및 구두점 정리
    t = re.sub(r"\s+([.,!?;:])", r"\1", t)
    t = re.sub(r"([(\[{<])\s+", r"\1", t)
    t = re.sub(r"\s+([)\]}>])", r"\1", t)
    t = re.sub(r"[ \t]+", " ", t)
    return t.strip()
